databases:
  - name: crm-db
    plan: free
    databaseName: crm
    user: crm_user

services:
  - type: web
    plan: free
    name: crm-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn crm_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
