# Generated by Django 5.2.14 on 2026-06-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('lead', 'Lead')], default='lead', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
                ('direccion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunion'), ('nota', 'Nota')], default='nota', max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.contacto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='crm.empresa'),
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('etapa', models.CharField(choices=[('prospecto', 'Prospecto'), ('cualificado', 'Cualificado'), ('propuesta', 'Propuesta'), ('cerrado_ganado', 'Cerrado Ganado'), ('cerrado_perdido', 'Cerrado Perdido')], default='prospecto', max_length=20)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.empresa')),
            ],
            options={
                'verbose_name_plural': 'oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
